import {
  AuthError,
  checkPassword,
  fetchAppleKeys,
  hashPassword,
  hashToken,
  newSessionToken,
  verifyAppleIdentityToken,
  type JwksFetcher,
} from "./auth";
import { ensureSchema, isoNow } from "./db";
import { HttpError, json, readJson, text } from "./http";
import { filterText } from "./moderation";

/**
 * Accountability between friends: accounts, friend codes, a friends-only
 * feed of what people actually did (auto-generated by the app, never free
 * text), cheers, and preset nudges. No public profiles, no follower counts,
 * no strangers — everything is visible only to accepted friends.
 */

export interface CommunityEnv {
  DB: D1Database;
  APPLE_BUNDLE_ID: string;
  AUTH_LIMITER: RateLimit;
  IP_LIMITER: RateLimit;
}

export interface UserRow {
  id: string;
  email: string | null;
  password_hash: string | null;
  apple_sub: string | null;
  name: string;
  handle: string;
  identity: string;
  friend_code: string;
  created_at: string;
  avatar_id: string | null;
  location: string;
  bio: string;
  goal: string;
  notify_prefs: string;
}

/** Which in-app notifications someone wants. Missing keys mean yes. */
export const NOTIFY_KEYS = ["friends", "nudges", "cheers", "comments", "messages"] as const;
type NotifyKey = (typeof NOTIFY_KEYS)[number];

export function parsePrefs(raw: string | null | undefined): Record<NotifyKey, boolean> {
  let parsed: Record<string, unknown> = {};
  try {
    parsed = JSON.parse(raw || "{}");
  } catch {
    // treat as defaults
  }
  return Object.fromEntries(NOTIFY_KEYS.map((key) => [key, parsed[key] !== false])) as Record<NotifyKey, boolean>;
}

export const EVENT_KINDS = ["wake", "run", "workout", "sleep", "habit", "milestone"] as const;
export const CHEERS = ["🔥", "👏", "💪", "☀️"] as const;
export const NUDGES: Record<string, string> = {
  wake: "Rise and shine ☀️",
  move: "Time to move 🏃",
  proud: "Proud of you 💪",
  together: "Let's do it together 🤝",
};

const FEED_DAYS = 14;
const FRIEND_LIMIT = 150;
const CODE_ALPHABET = "23456789ABCDEFGHJKMNPQRSTUVWXYZ"; // no 0/O, 1/I/L
const HANDLE = /^[a-z0-9_]{3,20}$/;
const EMAIL = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

// MARK: - Helpers

export function publicUser(user: UserRow) {
  return {
    id: user.id,
    name: user.name,
    handle: user.handle,
    identity: user.identity,
    avatar_id: user.avatar_id ?? null,
    location: user.location ?? "",
  };
}

function me(user: UserRow) {
  return {
    ...publicUser(user),
    email: user.email,
    friend_code: user.friend_code,
    has_apple: user.apple_sub !== null,
    bio: user.bio ?? "",
    goal: user.goal ?? "",
    notify_prefs: parsePrefs(user.notify_prefs),
  };
}

const NOTIFICATION_PREF: Record<string, NotifyKey> = {
  friend_request: "friends",
  friend_accepted: "friends",
  nudge: "nudges",
  cheer: "cheers",
  kudos: "cheers",
  comment: "comments",
};

/** Record something for `recipient`'s bell — unless they've turned that kind off. */
export async function notify(
  db: D1Database,
  recipient: string,
  actor: string,
  type: keyof typeof NOTIFICATION_PREF,
  extras: { postId?: string; text?: string } = {},
): Promise<void> {
  if (recipient === actor) return;
  const row = await db.prepare("SELECT notify_prefs FROM users WHERE id = ?").bind(recipient).first<{ notify_prefs: string }>();
  if (!row || !parsePrefs(row.notify_prefs)[NOTIFICATION_PREF[type]]) return;
  await db
    .prepare("INSERT INTO notifications (id, user_id, actor_id, type, post_id, text, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)")
    .bind(crypto.randomUUID(), recipient, actor, type, extras.postId ?? null, extras.text ?? "", isoNow())
    .run();
}

/** True if either person has blocked the other. */
export async function isBlocked(db: D1Database, a: string, b: string): Promise<boolean> {
  const row = await db
    .prepare("SELECT 1 FROM blocks WHERE (blocker_id = ? AND blocked_id = ?) OR (blocker_id = ? AND blocked_id = ?)")
    .bind(a, b, b, a)
    .first();
  return row !== null;
}

function randomCode(length: number): string {
  const bytes = crypto.getRandomValues(new Uint8Array(length));
  return [...bytes].map((b) => CODE_ALPHABET[b % CODE_ALPHABET.length]).join("");
}

async function limitAuth(request: Request, env: CommunityEnv): Promise<void> {
  const ip = request.headers.get("cf-connecting-ip") ?? "unknown";
  const { success } = await env.AUTH_LIMITER.limit({ key: ip });
  if (!success) throw new HttpError(429, "rate_limited", "Too many attempts — wait a minute and try again.");
}

async function limitIP(request: Request, env: CommunityEnv): Promise<void> {
  const ip = request.headers.get("cf-connecting-ip") ?? "unknown";
  const { success } = await env.IP_LIMITER.limit({ key: ip });
  if (!success) throw new HttpError(429, "rate_limited", "Slow down a little — try again in a minute.");
}

async function uniqueHandle(db: D1Database, name: string): Promise<string> {
  const base =
    name
      .toLowerCase()
      .normalize("NFKD")
      .replace(/[^a-z0-9]+/g, "")
      .slice(0, 14) || "flexer";
  for (let attempt = 0; attempt < 8; attempt++) {
    const candidate = attempt === 0 && base.length >= 3 ? base : `${base}${Math.floor(Math.random() * 9000 + 1000)}`;
    const taken = await db.prepare("SELECT 1 FROM users WHERE handle = ?").bind(candidate).first();
    if (!taken) return candidate;
  }
  return `${base}${randomCode(6).toLowerCase()}`;
}

async function uniqueFriendCode(db: D1Database): Promise<string> {
  for (;;) {
    const code = randomCode(6);
    const taken = await db.prepare("SELECT 1 FROM users WHERE friend_code = ?").bind(code).first();
    if (!taken) return code;
  }
}

async function createUser(
  db: D1Database,
  fields: { name: string; email: string | null; passwordHash: string | null; appleSub: string | null },
): Promise<UserRow> {
  const user: UserRow = {
    id: crypto.randomUUID(),
    email: fields.email,
    password_hash: fields.passwordHash,
    apple_sub: fields.appleSub,
    name: fields.name || "FlexUp friend",
    handle: await uniqueHandle(db, fields.name),
    identity: "",
    friend_code: await uniqueFriendCode(db),
    created_at: isoNow(),
    avatar_id: null,
    location: "",
    bio: "",
    goal: "",
    notify_prefs: "{}",
  };
  await db
    .prepare(
      `INSERT INTO users (id, email, password_hash, apple_sub, name, handle, identity, friend_code, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    )
    .bind(user.id, user.email, user.password_hash, user.apple_sub, user.name, user.handle, user.identity, user.friend_code, user.created_at)
    .run();
  return user;
}

async function startSession(db: D1Database, user: UserRow) {
  const token = newSessionToken();
  await db
    .prepare("INSERT INTO sessions (token_hash, user_id, created_at) VALUES (?, ?, ?)")
    .bind(await hashToken(token), user.id, isoNow())
    .run();
  return { token, user: me(user) };
}

/** The signed-in user, from `Authorization: Bearer <token>`. */
export async function requireUser(request: Request, env: CommunityEnv): Promise<UserRow> {
  const header = request.headers.get("authorization") ?? "";
  const token = header.startsWith("Bearer ") ? header.slice(7).trim() : "";
  if (!/^[0-9a-f]{64}$/.test(token)) throw new HttpError(401, "signed_out", "Please sign in again.");
  const user = await env.DB.prepare(
    "SELECT u.* FROM sessions s JOIN users u ON u.id = s.user_id WHERE s.token_hash = ?",
  )
    .bind(await hashToken(token))
    .first<UserRow>();
  if (!user) throw new HttpError(401, "signed_out", "Please sign in again.");
  return user;
}

export async function areFriends(db: D1Database, a: string, b: string): Promise<boolean> {
  return (await db.prepare("SELECT 1 FROM friendships WHERE user_id = ? AND friend_id = ?").bind(a, b).first()) !== null;
}

async function befriend(db: D1Database, a: string, b: string): Promise<void> {
  const now = isoNow();
  await db.batch([
    db.prepare("INSERT OR IGNORE INTO friendships (user_id, friend_id, created_at) VALUES (?, ?, ?)").bind(a, b, now),
    db.prepare("INSERT OR IGNORE INTO friendships (user_id, friend_id, created_at) VALUES (?, ?, ?)").bind(b, a, now),
    db.prepare("DELETE FROM friend_requests WHERE (from_id = ? AND to_id = ?) OR (from_id = ? AND to_id = ?)").bind(a, b, b, a),
  ]);
}

// MARK: - Auth

async function signUp(request: Request, env: CommunityEnv): Promise<Response> {
  await limitAuth(request, env);
  const body = await readJson(request);
  const email = text(body.email, 200).toLowerCase();
  const password = typeof body.password === "string" ? body.password : "";
  const name = text(body.name, 40);
  if (!EMAIL.test(email)) throw new HttpError(400, "bad_email", "That email doesn't look right.");
  if (password.length < 8 || password.length > 200) {
    throw new HttpError(400, "weak_password", "Use at least 8 characters for your password.");
  }
  if (!name) throw new HttpError(400, "bad_name", "Add your name so friends know it's you.");

  const existing = await env.DB.prepare("SELECT 1 FROM users WHERE email = ?").bind(email).first();
  if (existing) throw new HttpError(409, "email_taken", "There's already an account with that email — log in instead.");

  const user = await createUser(env.DB, { name: filterText(name), email, passwordHash: await hashPassword(password), appleSub: null });
  return json(await startSession(env.DB, user));
}

async function logIn(request: Request, env: CommunityEnv): Promise<Response> {
  await limitAuth(request, env);
  const body = await readJson(request);
  const email = text(body.email, 200).toLowerCase();
  const password = typeof body.password === "string" ? body.password : "";
  const user = await env.DB.prepare("SELECT * FROM users WHERE email = ?").bind(email).first<UserRow>();
  if (!user || !user.password_hash || !(await checkPassword(password, user.password_hash))) {
    throw new HttpError(401, "bad_credentials", "That email and password don't match.");
  }
  return json(await startSession(env.DB, user));
}

async function appleSignIn(request: Request, env: CommunityEnv, fetchKeys: JwksFetcher): Promise<Response> {
  await limitAuth(request, env);
  const body = await readJson(request);
  const token = typeof body.identity_token === "string" ? body.identity_token : "";
  let identity;
  try {
    identity = await verifyAppleIdentityToken(token, env.APPLE_BUNDLE_ID, fetchKeys);
  } catch (error) {
    if (error instanceof AuthError) throw new HttpError(401, "apple_rejected", "Apple sign-in couldn't be verified — try again.");
    throw error;
  }

  const existing = await env.DB.prepare("SELECT * FROM users WHERE apple_sub = ?").bind(identity.sub).first<UserRow>();
  if (existing) return json({ ...(await startSession(env.DB, existing)), is_new: false });

  // Apple only sends the name on the very first sign-in, so the app passes it along.
  const name = text(body.name, 40);
  // Don't claim an email that already belongs to a password account.
  const emailTaken = identity.email
    ? await env.DB.prepare("SELECT 1 FROM users WHERE email = ?").bind(identity.email.toLowerCase()).first()
    : null;
  const user = await createUser(env.DB, {
    name,
    email: identity.email && !emailTaken ? identity.email.toLowerCase() : null,
    passwordHash: null,
    appleSub: identity.sub,
  });
  return json({ ...(await startSession(env.DB, user)), is_new: true });
}

async function logOut(request: Request, env: CommunityEnv): Promise<Response> {
  const header = request.headers.get("authorization") ?? "";
  const token = header.startsWith("Bearer ") ? header.slice(7).trim() : "";
  if (token) await env.DB.prepare("DELETE FROM sessions WHERE token_hash = ?").bind(await hashToken(token)).run();
  return json({ ok: true });
}

// MARK: - Me

async function getMe(request: Request, env: CommunityEnv): Promise<Response> {
  return json({ user: me(await requireUser(request, env)) });
}

async function updateMe(request: Request, env: CommunityEnv): Promise<Response> {
  const user = await requireUser(request, env);
  const body = await readJson(request);

  const name = body.name === undefined ? user.name : text(body.name, 40);
  if (!name) throw new HttpError(400, "bad_name", "Your name can't be empty.");
  const identity = body.identity === undefined ? user.identity : text(body.identity, 80);
  let handle = user.handle;
  if (body.handle !== undefined) {
    handle = text(body.handle, 30).toLowerCase().replace(/^@/, "");
    if (!HANDLE.test(handle)) {
      throw new HttpError(400, "bad_handle", "Handles are 3–20 letters, numbers or underscores.");
    }
    if (handle !== user.handle) {
      const taken = await env.DB.prepare("SELECT 1 FROM users WHERE handle = ?").bind(handle).first();
      if (taken) throw new HttpError(409, "handle_taken", `@${handle} is taken — try another.`);
    }
  }

  const location = body.location === undefined ? user.location : filterText(text(body.location, 60));
  const bio = body.bio === undefined ? user.bio : filterText(text(body.bio, 160));
  const goal = body.goal === undefined ? user.goal : filterText(text(body.goal, 80));

  let avatarId = user.avatar_id;
  if (body.avatar_id !== undefined) {
    if (body.avatar_id === null) {
      avatarId = null;
    } else {
      const candidate = text(body.avatar_id, 64);
      const owned = await env.DB.prepare("SELECT 1 FROM images WHERE id = ? AND user_id = ?").bind(candidate, user.id).first();
      if (!owned) throw new HttpError(400, "bad_request", "That photo didn't upload — try again.");
      avatarId = candidate;
    }
  }

  let prefs = user.notify_prefs;
  if (body.notify_prefs !== undefined && typeof body.notify_prefs === "object" && body.notify_prefs !== null) {
    const incoming = body.notify_prefs as Record<string, unknown>;
    prefs = JSON.stringify(
      Object.fromEntries(NOTIFY_KEYS.map((key) => [key, incoming[key] === undefined ? parsePrefs(user.notify_prefs)[key] : incoming[key] !== false])),
    );
  }

  const cleanName = filterText(name);
  const cleanIdentity = filterText(identity);
  await env.DB.prepare(
    "UPDATE users SET name = ?, handle = ?, identity = ?, location = ?, bio = ?, goal = ?, avatar_id = ?, notify_prefs = ? WHERE id = ?",
  )
    .bind(cleanName, handle, cleanIdentity, location, bio, goal, avatarId, prefs, user.id)
    .run();
  if (user.avatar_id && user.avatar_id !== avatarId) {
    await env.DB.prepare("DELETE FROM images WHERE id = ? AND user_id = ?").bind(user.avatar_id, user.id).run();
  }
  return json({
    user: me({ ...user, name: cleanName, handle, identity: cleanIdentity, location, bio, goal, avatar_id: avatarId, notify_prefs: prefs }),
  });
}

/** Required by the App Store for any app that creates accounts. Removes everything. */
async function deleteMe(request: Request, env: CommunityEnv): Promise<Response> {
  const user = await requireUser(request, env);
  const id = user.id;
  await env.DB.batch([
    env.DB.prepare("DELETE FROM post_kudos WHERE user_id = ? OR post_id IN (SELECT id FROM posts WHERE user_id = ?)").bind(id, id),
    env.DB.prepare("DELETE FROM comments WHERE user_id = ? OR post_id IN (SELECT id FROM posts WHERE user_id = ?)").bind(id, id),
    env.DB.prepare("DELETE FROM notifications WHERE user_id = ? OR actor_id = ?").bind(id, id),
    env.DB.prepare("DELETE FROM posts WHERE user_id = ?").bind(id),
    env.DB.prepare("DELETE FROM images WHERE user_id = ?").bind(id),
    env.DB.prepare("DELETE FROM messages WHERE from_id = ? OR to_id = ?").bind(id, id),
    env.DB.prepare("DELETE FROM blocks WHERE blocker_id = ? OR blocked_id = ?").bind(id, id),
    env.DB.prepare("DELETE FROM reports WHERE reporter_id = ?").bind(id),
    env.DB.prepare("DELETE FROM cheers WHERE user_id = ? OR event_id IN (SELECT id FROM events WHERE user_id = ?)").bind(id, id),
    env.DB.prepare("DELETE FROM events WHERE user_id = ?").bind(id),
    env.DB.prepare("DELETE FROM nudges WHERE from_id = ? OR to_id = ?").bind(id, id),
    env.DB.prepare("DELETE FROM friend_requests WHERE from_id = ? OR to_id = ?").bind(id, id),
    env.DB.prepare("DELETE FROM friendships WHERE user_id = ? OR friend_id = ?").bind(id, id),
    env.DB.prepare("DELETE FROM sessions WHERE user_id = ?").bind(id),
    env.DB.prepare("DELETE FROM users WHERE id = ?").bind(id),
  ]);
  return json({ ok: true });
}

// MARK: - Friends

async function listFriends(request: Request, env: CommunityEnv): Promise<Response> {
  const user = await requireUser(request, env);
  const day = text(new URL(request.url).searchParams.get("day"), 12);

  const friends = await env.DB.prepare(
    `SELECT u.* FROM friendships f JOIN users u ON u.id = f.friend_id WHERE f.user_id = ? ORDER BY u.name COLLATE NOCASE`,
  )
    .bind(user.id)
    .all<UserRow>();
  const incoming = await env.DB.prepare(
    `SELECT u.* FROM friend_requests r JOIN users u ON u.id = r.from_id WHERE r.to_id = ? ORDER BY r.created_at DESC`,
  )
    .bind(user.id)
    .all<UserRow>();
  const outgoing = await env.DB.prepare(
    `SELECT u.* FROM friend_requests r JOIN users u ON u.id = r.to_id WHERE r.from_id = ? ORDER BY r.created_at DESC`,
  )
    .bind(user.id)
    .all<UserRow>();

  const ids = JSON.stringify(friends.results.map((f) => f.id));
  const [todayKinds, lastActive, wakeStreaks, nudged] = await Promise.all([
    env.DB.prepare(
      `SELECT user_id, kind FROM events WHERE day = ? AND user_id IN (SELECT value FROM json_each(?)) GROUP BY user_id, kind`,
    )
      .bind(day, ids)
      .all<{ user_id: string; kind: string }>(),
    env.DB.prepare(
      `SELECT user_id, MAX(occurred_at) AS at FROM events WHERE user_id IN (SELECT value FROM json_each(?)) GROUP BY user_id`,
    )
      .bind(ids)
      .all<{ user_id: string; at: string }>(),
    env.DB.prepare(
      `SELECT user_id, streak, MAX(occurred_at) AS at FROM events
       WHERE kind = 'wake' AND user_id IN (SELECT value FROM json_each(?)) GROUP BY user_id`,
    )
      .bind(ids)
      .all<{ user_id: string; streak: number | null; at: string }>(),
    env.DB.prepare(`SELECT to_id FROM nudges WHERE from_id = ? AND day = ?`).bind(user.id, day).all<{ to_id: string }>(),
  ]);

  const kindsByUser = new Map<string, string[]>();
  for (const row of todayKinds.results) kindsByUser.set(row.user_id, [...(kindsByUser.get(row.user_id) ?? []), row.kind]);
  const lastByUser = new Map(lastActive.results.map((row) => [row.user_id, row.at]));
  const streakByUser = new Map(wakeStreaks.results.map((row) => [row.user_id, row.streak]));
  const nudgedSet = new Set(nudged.results.map((row) => row.to_id));

  return json({
    friends: friends.results.map((friend) => ({
      user: publicUser(friend),
      today: kindsByUser.get(friend.id) ?? [],
      last_active_at: lastByUser.get(friend.id) ?? null,
      wake_streak: streakByUser.get(friend.id) ?? null,
      nudged_today: nudgedSet.has(friend.id),
    })),
    incoming: incoming.results.map(publicUser),
    outgoing: outgoing.results.map(publicUser),
  });
}

async function addFriend(request: Request, env: CommunityEnv): Promise<Response> {
  const user = await requireUser(request, env);
  await limitIP(request, env);
  const query = text((await readJson(request)).query, 40);
  const cleaned = query.replace(/^@/, "").replace(/^flex-/i, "");

  const target = await env.DB.prepare("SELECT * FROM users WHERE friend_code = ? OR handle = ?")
    .bind(cleaned.toUpperCase(), cleaned.toLowerCase())
    .first<UserRow>();
  if (!target) throw new HttpError(404, "not_found", "No one with that code or handle — check it and try again.");
  if (target.id === user.id) throw new HttpError(400, "self", "That's you! Share your code with a friend instead.");
  if (await isBlocked(env.DB, user.id, target.id)) {
    throw new HttpError(404, "not_found", "No one with that code or handle — check it and try again.");
  }
  if (await areFriends(env.DB, user.id, target.id)) {
    return json({ status: "friends", user: publicUser(target) });
  }

  const count = await env.DB.prepare("SELECT COUNT(*) AS n FROM friendships WHERE user_id = ?").bind(user.id).first<{ n: number }>();
  if ((count?.n ?? 0) >= FRIEND_LIMIT) throw new HttpError(400, "too_many", "That's a big crew — remove someone first.");

  // They already asked you: that's a yes from both sides.
  const theirRequest = await env.DB.prepare("SELECT 1 FROM friend_requests WHERE from_id = ? AND to_id = ?")
    .bind(target.id, user.id)
    .first();
  if (theirRequest) {
    await befriend(env.DB, user.id, target.id);
    await notify(env.DB, target.id, user.id, "friend_accepted");
    return json({ status: "friends", user: publicUser(target) });
  }

  const inserted = await env.DB.prepare("INSERT OR IGNORE INTO friend_requests (from_id, to_id, created_at) VALUES (?, ?, ?)")
    .bind(user.id, target.id, isoNow())
    .run();
  if (inserted.meta.changes > 0) await notify(env.DB, target.id, user.id, "friend_request");
  return json({ status: "requested", user: publicUser(target) });
}

async function respondToFriend(request: Request, env: CommunityEnv): Promise<Response> {
  const user = await requireUser(request, env);
  const body = await readJson(request);
  const fromId = text(body.user_id, 64);
  const request_ = await env.DB.prepare("SELECT 1 FROM friend_requests WHERE from_id = ? AND to_id = ?")
    .bind(fromId, user.id)
    .first();
  if (!request_) throw new HttpError(404, "not_found", "That request is gone.");

  if (body.accept === true) {
    await befriend(env.DB, user.id, fromId);
    await notify(env.DB, fromId, user.id, "friend_accepted");
  } else {
    await env.DB.prepare("DELETE FROM friend_requests WHERE from_id = ? AND to_id = ?").bind(fromId, user.id).run();
  }
  return json({ ok: true });
}

/** Unfriend, cancel a sent request, or decline — and hide each other's history. */
async function removeFriend(request: Request, env: CommunityEnv): Promise<Response> {
  const user = await requireUser(request, env);
  const other = text((await readJson(request)).user_id, 64);
  await env.DB.batch([
    env.DB.prepare("DELETE FROM friendships WHERE (user_id = ? AND friend_id = ?) OR (user_id = ? AND friend_id = ?)").bind(
      user.id,
      other,
      other,
      user.id,
    ),
    env.DB.prepare("DELETE FROM friend_requests WHERE (from_id = ? AND to_id = ?) OR (from_id = ? AND to_id = ?)").bind(
      user.id,
      other,
      other,
      user.id,
    ),
  ]);
  return json({ ok: true });
}

// MARK: - Feed

async function postEvent(request: Request, env: CommunityEnv): Promise<Response> {
  const user = await requireUser(request, env);
  const body = await readJson(request);
  const kind = text(body.kind, 20);
  if (!(EVENT_KINDS as readonly string[]).includes(kind)) throw new HttpError(400, "bad_request", "Unknown activity.");
  const clientId = text(body.client_id, 64);
  const title = text(body.title, 80);
  const day = text(body.day, 12);
  const occurredAt = text(body.occurred_at, 30);
  if (!clientId || !title || !day || Number.isNaN(Date.parse(occurredAt))) {
    throw new HttpError(400, "bad_request", "Couldn't read the activity.");
  }
  const streak = typeof body.streak === "number" && Number.isFinite(body.streak) ? Math.max(0, Math.floor(body.streak)) : null;

  const id = crypto.randomUUID();
  await env.DB.prepare(
    `INSERT OR IGNORE INTO events (id, user_id, client_id, kind, title, detail, day, streak, occurred_at, created_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
  )
    .bind(id, user.id, clientId, kind, title, text(body.detail, 120), day, streak, occurredAt, isoNow())
    .run();
  return json({ ok: true });
}

async function getFeed(request: Request, env: CommunityEnv): Promise<Response> {
  const user = await requireUser(request, env);
  const since = isoNow(new Date(Date.now() - FEED_DAYS * 86_400_000));
  const events = await env.DB.prepare(
    `SELECT e.id, e.user_id, e.kind, e.title, e.detail, e.streak, e.occurred_at, u.name, u.handle, u.avatar_id
     FROM events e JOIN users u ON u.id = e.user_id
     WHERE (e.user_id = ?1 OR e.user_id IN (SELECT friend_id FROM friendships WHERE user_id = ?1))
       AND e.occurred_at >= ?2
     ORDER BY e.occurred_at DESC LIMIT 100`,
  )
    .bind(user.id, since)
    .all<{
      id: string;
      user_id: string;
      kind: string;
      title: string;
      detail: string;
      streak: number | null;
      occurred_at: string;
      name: string;
      handle: string;
      avatar_id: string | null;
    }>();

  const cheers = await env.DB.prepare(
    `SELECT c.event_id, c.user_id, c.emoji, u.name FROM cheers c JOIN users u ON u.id = c.user_id
     WHERE c.event_id IN (SELECT value FROM json_each(?)) ORDER BY c.created_at`,
  )
    .bind(JSON.stringify(events.results.map((e) => e.id)))
    .all<{ event_id: string; user_id: string; emoji: string; name: string }>();

  const cheersByEvent = new Map<string, { user_id: string; emoji: string; name: string }[]>();
  for (const cheer of cheers.results) {
    cheersByEvent.set(cheer.event_id, [...(cheersByEvent.get(cheer.event_id) ?? []), cheer]);
  }

  return json({
    events: events.results.map((event) => {
      const eventCheers = cheersByEvent.get(event.id) ?? [];
      return {
        id: event.id,
        user: { id: event.user_id, name: event.name, handle: event.handle, avatar_id: event.avatar_id },
        kind: event.kind,
        title: event.title,
        detail: event.detail,
        streak: event.streak,
        occurred_at: event.occurred_at,
        is_mine: event.user_id === user.id,
        my_cheer: eventCheers.find((c) => c.user_id === user.id)?.emoji ?? null,
        cheers: eventCheers.map((c) => ({ name: c.user_id === user.id ? "You" : c.name, emoji: c.emoji })),
      };
    }),
  });
}

async function cheer(request: Request, env: CommunityEnv): Promise<Response> {
  const user = await requireUser(request, env);
  const body = await readJson(request);
  const eventId = text(body.event_id, 64);
  const event = await env.DB.prepare("SELECT user_id FROM events WHERE id = ?").bind(eventId).first<{ user_id: string }>();
  if (!event || (event.user_id !== user.id && !(await areFriends(env.DB, user.id, event.user_id)))) {
    throw new HttpError(404, "not_found", "That's no longer here.");
  }

  if (body.emoji === null) {
    await env.DB.prepare("DELETE FROM cheers WHERE event_id = ? AND user_id = ?").bind(eventId, user.id).run();
    return json({ ok: true });
  }
  const emoji = text(body.emoji, 8);
  if (!(CHEERS as readonly string[]).includes(emoji)) throw new HttpError(400, "bad_request", "Unknown cheer.");
  await env.DB.prepare(
    `INSERT INTO cheers (event_id, user_id, emoji, created_at) VALUES (?, ?, ?, ?)
     ON CONFLICT (event_id, user_id) DO UPDATE SET emoji = excluded.emoji`,
  )
    .bind(eventId, user.id, emoji, isoNow())
    .run();
  const title = await env.DB.prepare("SELECT title FROM events WHERE id = ?").bind(eventId).first<{ title: string }>();
  await notify(env.DB, event.user_id, user.id, "cheer", { text: `${emoji} ${title?.title ?? ""}`.trim() });
  return json({ ok: true });
}

// MARK: - Nudges

async function sendNudge(request: Request, env: CommunityEnv): Promise<Response> {
  const user = await requireUser(request, env);
  const body = await readJson(request);
  const to = text(body.to, 64);
  const kind = text(body.kind, 20);
  const day = text(body.day, 12);
  if (!NUDGES[kind] || !day) throw new HttpError(400, "bad_request", "Unknown nudge.");
  if (!(await areFriends(env.DB, user.id, to))) throw new HttpError(404, "not_found", "You can only nudge friends.");

  const result = await env.DB.prepare(
    "INSERT OR IGNORE INTO nudges (id, from_id, to_id, kind, day, created_at) VALUES (?, ?, ?, ?, ?, ?)",
  )
    .bind(crypto.randomUUID(), user.id, to, kind, day, isoNow())
    .run();
  if (result.meta.changes === 0) {
    throw new HttpError(409, "already_nudged", "You've already nudged them today — one's enough.");
  }
  await notify(env.DB, to, user.id, "nudge", { text: NUDGES[kind] });
  return json({ ok: true });
}

async function listNudges(request: Request, env: CommunityEnv): Promise<Response> {
  const user = await requireUser(request, env);
  const since = isoNow(new Date(Date.now() - 7 * 86_400_000));
  const nudges = await env.DB.prepare(
    `SELECT n.id, n.kind, n.created_at, u.id AS from_id, u.name, u.handle, u.avatar_id FROM nudges n JOIN users u ON u.id = n.from_id
     WHERE n.to_id = ? AND n.seen_at IS NULL AND n.created_at >= ? ORDER BY n.created_at DESC LIMIT 20`,
  )
    .bind(user.id, since)
    .all<{ id: string; kind: string; created_at: string; from_id: string; name: string; handle: string; avatar_id: string | null }>();
  return json({
    nudges: nudges.results.map((n) => ({
      id: n.id,
      from: { id: n.from_id, name: n.name, handle: n.handle, avatar_id: n.avatar_id },
      kind: n.kind,
      message: NUDGES[n.kind] ?? "",
      created_at: n.created_at,
    })),
  });
}

async function markNudgesSeen(request: Request, env: CommunityEnv): Promise<Response> {
  const user = await requireUser(request, env);
  const ids = (await readJson(request)).ids;
  if (!Array.isArray(ids)) throw new HttpError(400, "bad_request", "Couldn't read the request.");
  await env.DB.prepare(
    "UPDATE nudges SET seen_at = ? WHERE to_id = ? AND id IN (SELECT value FROM json_each(?))",
  )
    .bind(isoNow(), user.id, JSON.stringify(ids.filter((id) => typeof id === "string").slice(0, 50)))
    .run();
  return json({ ok: true });
}

// MARK: - Routes

export type Params = Record<string, string>;
export type Handler = (request: Request, env: CommunityEnv, params: Params) => Promise<Response>;

export function communityRoutes(fetchKeys: JwksFetcher = fetchAppleKeys): Record<string, Handler> {
  const withSchema =
    (handler: Handler): Handler =>
    async (request, env, params) => {
      await ensureSchema(env.DB);
      return handler(request, env, params);
    };
  return {
    "POST /v1/auth/signup": withSchema(signUp),
    "POST /v1/auth/login": withSchema(logIn),
    "POST /v1/auth/apple": withSchema((request, env) => appleSignIn(request, env, fetchKeys)),
    "POST /v1/auth/logout": withSchema(logOut),
    "GET /v1/me": withSchema(getMe),
    "POST /v1/me": withSchema(updateMe),
    "POST /v1/me/delete": withSchema(deleteMe),
    "GET /v1/friends": withSchema(listFriends),
    "POST /v1/friends/add": withSchema(addFriend),
    "POST /v1/friends/respond": withSchema(respondToFriend),
    "POST /v1/friends/remove": withSchema(removeFriend),
    "GET /v1/feed": withSchema(getFeed),
    "POST /v1/events": withSchema(postEvent),
    "POST /v1/events/cheer": withSchema(cheer),
    "GET /v1/nudges": withSchema(listNudges),
    "POST /v1/nudges": withSchema(sendNudge),
    "POST /v1/nudges/seen": withSchema(markNudgesSeen),
  };
}
