import Foundation

// Shapes returned by the FlexUp server's community endpoints (see
// `backend/src/community.ts`). Decoded with `.convertFromSnakeCase` and
// `.iso8601` dates — keep both sides in sync.

struct CommunityUser: Codable, Hashable, Identifiable {
    let id: String
    let name: String
    let handle: String
    /// "Becoming …" line. Absent where the server sends a compact user.
    let identity: String?
    /// Profile photo, served at `/v1/images/<id>`.
    let avatarId: String?
    let location: String?

    init(id: String, name: String, handle: String, identity: String? = nil, avatarId: String? = nil, location: String? = nil) {
        self.id = id
        self.name = name
        self.handle = handle
        self.identity = identity
        self.avatarId = avatarId
        self.location = location
    }
}

/// The signed-in person, as the server knows them.
struct CommunityMe: Codable, Hashable {
    let id: String
    let name: String
    let handle: String
    let identity: String
    let email: String?
    let friendCode: String
    let hasApple: Bool
    let avatarId: String?
    let location: String
    let bio: String
    let goal: String
    let notifyPrefs: NotifyPrefs

    var asUser: CommunityUser {
        CommunityUser(id: id, name: name, handle: handle, identity: identity, avatarId: avatarId, location: location)
    }
}

/// Which friend activity lands in your notification bell.
struct NotifyPrefs: Codable, Hashable {
    var friends = true
    var nudges = true
    var cheers = true
    var comments = true
    var messages = true
}

/// A friend plus what they've done today — the accountability row.
struct FriendStatus: Codable, Hashable, Identifiable {
    let user: CommunityUser
    let today: [String]
    let lastActiveAt: Date?
    let wakeStreak: Int?
    var nudgedToday: Bool

    var id: String { user.id }
    var todayKinds: [ActivityKind] { today.compactMap(ActivityKind.init(rawValue:)) }
}

struct FeedCheer: Codable, Hashable {
    let name: String
    let emoji: String
}

struct FeedEvent: Codable, Hashable, Identifiable {
    let id: String
    let user: CommunityUser
    let kind: String
    let title: String
    let detail: String
    let streak: Int?
    let occurredAt: Date
    let isMine: Bool
    var myCheer: String?
    var cheers: [FeedCheer]

    var activityKind: ActivityKind? { ActivityKind(rawValue: kind) }
}

struct Nudge: Codable, Hashable, Identifiable {
    let id: String
    let from: CommunityUser
    let kind: String
    let message: String
    let createdAt: Date
}

/// What gets shared with friends. Generated by the app from real logs —
/// never free text — so the feed is proof, not posts.
enum ActivityKind: String, Codable, CaseIterable, Identifiable {
    case wake, run, workout, sleep, habit, milestone

    var id: String { rawValue }

    var icon: String {
        switch self {
        case .wake: "sunrise.fill"
        case .run: "figure.run"
        case .workout: "dumbbell.fill"
        case .sleep: "moon.zzz.fill"
        case .habit: "checkmark.circle.fill"
        case .milestone: "star.fill"
        }
    }

    var label: String {
        switch self {
        case .wake: "Wake-ups"
        case .run: "Runs"
        case .workout: "Workouts"
        case .sleep: "Sleep"
        case .habit: "Habits done"
        case .milestone: "Milestones"
        }
    }
}

/// Preset nudges — no free text, so nothing needs moderating.
enum NudgeKind: String, CaseIterable, Identifiable {
    case wake, move, proud, together

    var id: String { rawValue }

    var message: String {
        switch self {
        case .wake: "Rise and shine ☀️"
        case .move: "Time to move 🏃"
        case .proud: "Proud of you 💪"
        case .together: "Let's do it together 🤝"
        }
    }
}

enum CommunityCheer {
    static let all = ["🔥", "👏", "💪", "☀️"]
}

/// Which pillars appear in your friends' feed. Diet is never shared.
struct SharingSettings: Codable, Hashable {
    var wake = true
    var run = true
    var workout = true
    var habit = true
    var sleep = false

    func allows(_ kind: ActivityKind) -> Bool {
        switch kind {
        case .wake: wake
        case .run: run
        case .workout: workout
        case .habit: habit
        case .sleep: sleep
        case .milestone: true
        }
    }
}

/// An activity waiting to reach the server. Queued on disk so a run logged
/// offline still shows up for friends later; `clientID` makes retries safe.
struct PendingActivity: Codable, Hashable {
    var clientID = UUID().uuidString
    var kind: ActivityKind
    var title: String
    var detail: String
    var day: String
    var occurredAt: Date
    var streak: Int?
}

// MARK: - Posts, comments, messages, notifications, profiles

struct Post: Codable, Hashable, Identifiable {
    let id: String
    let user: CommunityUser
    let text: String
    let imageId: String?
    let createdAt: Date
    let isMine: Bool
    var kudos: [CommunityUser]
    var gaveKudos: Bool
    var commentCount: Int
}

struct PostComment: Codable, Hashable, Identifiable {
    let id: String
    let text: String
    let createdAt: Date
    let user: CommunityUser
    let canDelete: Bool
}

struct AppNotification: Codable, Hashable, Identifiable {
    let id: String
    let type: String
    let postId: String?
    let text: String
    let createdAt: Date
    let isRead: Bool
    let actor: CommunityUser

    /// One line, written the way a friend would say it.
    var sentence: String {
        switch type {
        case "friend_request": "\(actor.name) wants to be accountability partners"
        case "friend_accepted": "\(actor.name) accepted. You're now in each other's crew"
        case "nudge": "\(actor.name) nudged you: \(text)"
        case "cheer": "\(actor.name) cheered \(text)"
        case "kudos": text.isEmpty ? "\(actor.name) gave you kudos" : "\(actor.name) gave kudos to “\(text)”"
        case "comment": "\(actor.name) commented: “\(text)”"
        default: "\(actor.name) \(text)"
        }
    }

    var icon: String {
        switch type {
        case "friend_request", "friend_accepted": "person.badge.plus"
        case "nudge": "hand.wave.fill"
        case "cheer": "flame.fill"
        case "kudos": "hand.thumbsup.fill"
        case "comment": "text.bubble.fill"
        default: "bell.fill"
        }
    }
}

struct MessageThread: Codable, Hashable, Identifiable {
    let user: CommunityUser
    let lastText: String?
    let lastAt: Date?
    let lastFromMe: Bool
    var unread: Int

    var id: String { user.id }
}

struct DirectMessage: Codable, Hashable, Identifiable {
    let id: String
    let text: String
    let createdAt: Date
    let fromMe: Bool
}

struct CommunityProfile: Codable, Hashable {
    let user: CommunityUser
    let bio: String
    let goal: String
    let joinedAt: Date
    /// "self", "friend", "incoming" (they asked you) or "outgoing" (you asked them).
    let relationship: String
    /// This month's shared activity counts, keyed by `ActivityKind` raw value.
    let month: [String: Int]
    let wakeStreak: Int?
}

struct Badges: Codable, Hashable {
    var notifications = 0
    var messages = 0
    var requests = 0
}

enum ReportReason: String, CaseIterable, Identifiable {
    case spam, harassment, hate, nudity, violence, other

    var id: String { rawValue }
    var label: String { rawValue.capitalized }
}
