import Foundation

// Shapes returned by the FlexUp server's community endpoints (see
// `backend/src/community.ts`). Decoded with `.convertFromSnakeCase` and
// `.iso8601` dates — keep both sides in sync.

struct CommunityUser: Codable, Hashable, Identifiable {
    let id: String
    let name: String
    let handle: String
    /// "Becoming …" line. Absent where the server sends a compact user.
    let identity: String?
}

/// The signed-in person, as the server knows them.
struct CommunityMe: Codable, Hashable {
    let id: String
    let name: String
    let handle: String
    let identity: String
    let email: String?
    let friendCode: String
    let hasApple: Bool
}

/// A friend plus what they've done today — the accountability row.
struct FriendStatus: Codable, Hashable, Identifiable {
    let user: CommunityUser
    let today: [String]
    let lastActiveAt: Date?
    let wakeStreak: Int?
    var nudgedToday: Bool

    var id: String { user.id }
    var todayKinds: [ActivityKind] { today.compactMap(ActivityKind.init(rawValue:)) }
}

struct FeedCheer: Codable, Hashable {
    let name: String
    let emoji: String
}

struct FeedEvent: Codable, Hashable, Identifiable {
    let id: String
    let user: CommunityUser
    let kind: String
    let title: String
    let detail: String
    let streak: Int?
    let occurredAt: Date
    let isMine: Bool
    var myCheer: String?
    var cheers: [FeedCheer]

    var activityKind: ActivityKind? { ActivityKind(rawValue: kind) }
}

struct Nudge: Codable, Hashable, Identifiable {
    let id: String
    let from: CommunityUser
    let kind: String
    let message: String
    let createdAt: Date
}

/// What gets shared with friends. Generated by the app from real logs —
/// never free text — so the feed is proof, not posts.
enum ActivityKind: String, Codable, CaseIterable, Identifiable {
    case wake, run, workout, sleep, habit, milestone

    var id: String { rawValue }

    var icon: String {
        switch self {
        case .wake: "sunrise.fill"
        case .run: "figure.run"
        case .workout: "dumbbell.fill"
        case .sleep: "moon.zzz.fill"
        case .habit: "checkmark.circle.fill"
        case .milestone: "star.fill"
        }
    }

    var label: String {
        switch self {
        case .wake: "Wake-ups"
        case .run: "Runs"
        case .workout: "Workouts"
        case .sleep: "Sleep"
        case .habit: "Habits done"
        case .milestone: "Milestones"
        }
    }
}

/// Preset nudges — no free text, so nothing needs moderating.
enum NudgeKind: String, CaseIterable, Identifiable {
    case wake, move, proud, together

    var id: String { rawValue }

    var message: String {
        switch self {
        case .wake: "Rise and shine ☀️"
        case .move: "Time to move 🏃"
        case .proud: "Proud of you 💪"
        case .together: "Let's do it together 🤝"
        }
    }
}

enum CommunityCheer {
    static let all = ["🔥", "👏", "💪", "☀️"]
}

/// Which pillars appear in your friends' feed. Diet is never shared.
struct SharingSettings: Codable, Hashable {
    var wake = true
    var run = true
    var workout = true
    var habit = true
    var sleep = false

    func allows(_ kind: ActivityKind) -> Bool {
        switch kind {
        case .wake: wake
        case .run: run
        case .workout: workout
        case .habit: habit
        case .sleep: sleep
        case .milestone: true
        }
    }
}

/// An activity waiting to reach the server. Queued on disk so a run logged
/// offline still shows up for friends later; `clientID` makes retries safe.
struct PendingActivity: Codable, Hashable {
    var clientID = UUID().uuidString
    var kind: ActivityKind
    var title: String
    var detail: String
    var day: String
    var occurredAt: Date
    var streak: Int?
}
